volumes:
  database:
    driver: local

services:
  mysql:
    platform: linux
    image: mysql
    container_name: app_mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASS}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASS}
    volumes:
      - database:/var/lib/mysql
